"""user table relationship

Revision ID: 65d01a4e9098
Revises: 2e653a9777f1
Create Date: 2024-08-31 01:27:25.115312

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "65d01a4e9098"
down_revision: Union[str, None] = "2e653a9777f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("owner_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        None, "task", "user", ["owner_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "task", type_="foreignkey")
    op.drop_column("task", "owner_id")
    # ### end Alembic commands ###
